#!/usr/bin/python3
import sys

def factorize(n):
	"""
	Factorize a number into two smaller numbers

	Args:
	- n (int): the number to factorize

	Return:
	- tuple: A tuple containing two factors.
	"""
	factors = []
	div = 2

	while div * div <= n:
		if n % div == 0:
			factors.append(div)
			n //= div
		else:
			div += 1
	if n > 1:
		factors.append(n)

	return factors

def main():
	if len(sys.argv) != 2:
		print("Usage: factors<file>")
		sys.exit(1)

	input_file = sys.argv[1]

	try:
		with open(input_file, 'r') as file:
			num = file.read().splitlines()
	except FileNotFoundError:
		print(f"Error: File 'input_file' not found")
		sys.exit(1)

	for n in num:
		y = int(n)
		factorized = factorize(y)

		if len(factorized) == 1:
			print(f"{y} is prime number")
		else:
			p, q = y // factorized[0], factorized[0]
			print(f"{n}={p}*{q}")

if __name__ == "__main__":
	main()
