#!/usr/bin/python3
import sys
from math import isqrt

def factorize(n):
	"""
	Factorize a number into two smaller numbers

	Args:
	- n (int): the number to factorize

	Return:
	- tuple: A tuple containing two factors.
	"""

	for i in range(2, isqrt(n) + 1):
		if n % i == 0:
			return i, n // i
	return n, 1

def main():
	if len(sys.argv) != 2:
		print("Usage: factors<file>")
		sys.exit(1)

	input_file = sys.argv[1]

	try:
		with open(input_file, 'r') as file:
			for line in file:
				num = int(line.strip())
				factor1, factor2 = factorize(num)
				print(f"{num}={factor2}*{factor1}")
	except FileNotFoundError:
		print(f"Error: File 'input_file' not found")

if __name__ == "__main__":
	main()
